version: '3.7'
services:
  web-view:
      build: web-view
      container_name: web
      ports:
        - "8080:80"
      restart: "no"
      volumes: 
      - ./web-view/:/code
  api-ml:
    build: api
    container_name: api-ml
    ports:
      - '8081:8080'
    volumes:
      - ./api:/code
    restart: "no"